# Using Spring boot with YAML
# DO NOT USE TABS
# Spacing is important, each line is indented by two spaces
guru:
  jms:
    username: JMS Username
    password: somepass
    url: someUrl

---           #Indicates a file separator inside YAML
spring:
  profiles: es #The spring profile overrides the other one
guru:
  jms:
    username: Nombre de usuario de JMS
    password: alguien pasa
    url: someUrl **In**Spanish
